### ISSUE TITLE
Refactor ContactType component

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/moira#280]
In [parent issue](https://github.com/moira-alert/moira/issues/123) I understood that in current version of ContactTypeIcon component we can't add another icon, because code will be mess.

So, it needs some refactoring.

### ToDo

- [x] Remove `Domain/ContactType.js` file
Enum `ContactTypeCaptions`, `ContactTypes` and getter `getContactTypeCaption` is useless now. Labels for contact type now will store on backend (in config)

- [x] Refactor `ContactEditForm.jsx`
Instead `getContactTypeCaption` use some placeholder (for example "Contact label"). **I'll replace it to real label from backend after closing this issue.**

- [x] Refactor `ContactTypeIcon.jsx`
Replace if chain to function, that try guess contact type and select icon. By default (if selection failed) this function must return default icon (envelop). Return type is React.Node. This logic of component must be saved.

- [x] Update config.json and docs

### Selection logic
If contact type contains substring:
- slack — return Slack icon `./slack-logo.svg`
- telegram — return Telegram icon `@skbkontur/react-icons/Telegram2`
- facebook — return Facebook icon `@skbkontur/react-icons/Facebook2`
- viber — return Viber icon `@skbkontur/react-icons/Viber2`
- whatsapp — return Whatsapp icon `@skbkontur/react-icons/WhatsApp2`
- twitter — return Twitter icon `@skbkontur/react-icons/Twitter2`
- mail or email — return envelope icon `@skbkontur/react-icons/Mail2`
- pushover — return Pushover icon `./pushover-logo.svg`
- twilio — return Twilio icon `./twilio-logo.svg`
- webhook — return Webhook icon. [Need download](https://icons8.com/icons/set/webhook) in Material Filled style and place in component folder
- phone or tel or sms — return phone icon `@skbkontur/react-icons/Phone2`

By default (if selection failed) component must return envelope icon `@skbkontur/react-icons/Mail2`

**Comment by Vivekrajput20** [comment]
I would like to work on the issue

**Comment by sashasushko** [comment]
Okay

**Comment by Vivekrajput20** [comment]
I'm having trouble setting up the project. Readme says cd docker-compose. But there is no docker-compose folder. Is there any other installation guide I can refer to?
Thanks

**Comment by sashasushko** [comment]
For web developing you need only Node.js and Yarn installed. Then follow the instruction [in web read.me](https://github.com/moira-alert/web2.0/blob/master/README.md#developing)

**Comment by Vivekrajput20** [comment]
@sashasushko in the third ToDo I installed the @skbkontur/react-icons package to use the icons. But when I tried to import the icons, it gave me the following error.
![image](https://user-images.githubusercontent.com/31074883/53810541-32f6ae80-3f7d-11e9-96e2-60afafafd7d8.png)

I think I'm supposed to update the webpack config to fix this error. Should I proceed further?

**Comment by sashasushko** [comment]
Hmm... Strange things. It's already been in develop branch. Can you describe by steps what are you doing? I try figure out tomorrow

**Comment by Vivekrajput20** [comment]
Sorry I was working on the master branch and faced the error. I have switched to develop now and will try to do it on develop branch

**Comment by sashasushko** [comment]
Cool. I'm just add [two our major contributing rules](https://github.com/moira-alert/web2.0/blob/develop/README.md#contributing)

**Comment by Vivekrajput20** [comment]
Also @skbkontur/react-icons don't have whatsapp and viber icons. I downloaded the whatsapp material filled icon from https://icons8.com/icons/ but unfortunately viber material filled icon isn't available there. What alternative should I use?

**Comment by Vivekrajput20** [comment]
@sashasushko  `ContactTypes` is being used in many files like `/src/Stories/ContactTypeIcon.stories.js`,
`/src/Stories/ContactList.stories.js`. Removing the `Domain/ContactType.js` requires changes in other files too. ` /src/Stories/ContactTypeIcon.stories.js` totally depends on `ContactTypes` and won't be functional after removing the `Domain/ContactType.js` file. What should I do?

**Comment by sashasushko** [comment]
> @skbkontur/react-icons don't have whatsapp and viber icons.

It's library bug. Please, code all logic, but return envelope icon (temporary solution) and add ToDo about it. We'll fix bug in library and complete ToDo. 

> ContactTypes is being used in many files
It's my loss. Keep it till I figured out how to be

**Comment by sashasushko** [comment]
> @skbkontur/react-icons don't have whatsapp and viber icons.

Try update `@skbkontur/react-icons` from 3.1.2 to 3.1.3
